@startuml

title tetris

start
    note right
        moveTetromino
        ※同様に、右の場合、下の場合も同じようなロジック
    endnote
    :引数を受け取る;
    if (左に移動可能である) then (true)
        :テトロミノを左に1マス移動する;
    endif
end

start
    note right
        deleteTetrominos
        テトロミノが1行満たされることで、
        削除可能かを判定する。
    endnote
    repeat
        if (recordがすべてテトロミノである) then (true)
            :recordのテトロミノを空にする;
            :すべてのテトロミノを下にずらす;
        endif
    repeat while (record : records)
end

start
    note right
        rotateTetorimino
        テトロミノを回転する。
        テトロミノは配列で保持していて、回転する場合は
        その配列インデクスを+1または-1することで実現する。
    endnote
    :テトロミノのインデクスを取得する;
    :rotateTetromino = tetrominoIndex + 1;
    note right
        左回転の場合は - 1
    endnote
    :tetromino = rotateTetromino;
    :画面の再描画;
end

start
    note right
        isPopableTetromino
        テトロミノを取得可能か判定する
    endnote
    :次のテトロミノを取得する
    (popではなくget);
    if (ゲーム板の一番上の中央に配置可能である) then (true)
        :return true;
        end
    endif
    :return false;
end

start
    note right
        popTetromino
        テトロミノを取得する
    endnote
    :テトロミノを取得する;
    :新規テトロミノを生成し、スタックにpushする;
end

start
    note right
        checkGameOver
    endnote
    if (isPoppableTetromino() == false) then (true)
        :gameover;
    endif
end

@enduml
